# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd864a6ce146fa7079b296e46cb7bdf631b24fac3188d9f847a410a0c3bfac5810e332040236327a90f43877d6eb83037f210942057fd124cc5f57d9a14ef479

test:
  secret_key_base: 1e0019adf03027a2c7ca6a71a3ba13d8748f6c92065b435cc9f0093e61af0b0ea0df861d23a027829d9a6b6e7244efd51d4e3ce4739307e160db0a303486b21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
